In [1]:
!pip install numpy pandas matplotlib

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 5.4 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.3 MB 11.8 MB/s eta 0:00:01
   ----------------------- ---------------- 7.1/12.3 MB 14.9 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 16.5 MB/s  0:00:00
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ----------- ---------------------------- 2.9/9.7 MB 24.9 MB/s eta 0:00:01
   ---------------- ----------------------- 3.9/9.7 MB 12.4 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 15.3 MB/s  0:00:00
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -------------- ------------------------- 2.9/8.1 MB 13.8 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.1 MB 14.1 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 13.5 MB/s  0:00:00
   ------------------------

In [6]:
# Task 1. Create Arrays

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Imports oke!")

Imports oke!


In [4]:
arr1 = np.arange(1, 11)
print("1d array:", arr1)

arr2 = np.random.randint(1, 101, size=(3, 3))
print("2d array:\n", arr2)

1d array: [ 1  2  3  4  5  6  7  8  9 10]
2d array:
 [[ 2 40 36]
 [86 47 41]
 [93 64 93]]


In [7]:
# Task 2: Array Operations

In [5]:
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Max:", arr1.max())

arr_mult = arr1 * 2
print("Multiply by 2:", arr_mult)

arr_replaced = arr1.copy()
arr_replaced[arr_replaced > 5] = 0
print("Replace > 5 with 0:", arr_replaced)

Sum: 55
Mean: 5.5
Max: 10
Multiply by 2: [ 2  4  6  8 10 12 14 16 18 20]
Replace > 5 with 0: [1 2 3 4 5 0 0 0 0 0]
